### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by my-empire26** [Link009/LPEX#1]
Traceback (most recent call last):
  File "Extraction.py", line 53, in <module>
    imageContours, contours, hierarchy = cv2.findContours(thresh, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)

Getting this Error can you please help me to solve this....

Thanks In Advance

**Comment by Link009** [comment]
Hi

Can you please try again now ? Also, can you post your Python, OpenCv and Windows version ? I think it's because of OpenCv that changed something under the hood. Let me know.

**Comment by my-empire26** [comment]
Python 3.7.2
OpenCV 4.1.0
windows 10
yes It's working Now but how do I display The character after the processing on the terminal... It's just detecting and displaying the image... 
Thanks a lot

**Comment by Link009** [comment]
It's not recognizing any character, just detecting plate area. For recognizing you can try [this](https://cvisiondemy.com/character-recognition-alpr-ocr-case/). It's just OCR, nothing advanced. You could finetune the code and see the results.

If you want to extract a single character, you could apply some preprocessing on the plate and then extract. But still not recognizing chars are being made on this code.

Chris Dahms did some recognition in his original code ([here](https://github.com/MicrocontrollersAndMore/OpenCV_3_License_Plate_Recognition_Python)) but removed that part because I don't need it just now.

**Comment by Link009** [comment]
Updated code.

**Comment by Link009** [comment]
> Traceback (most recent call last):
> File "Extraction.py", line 53, in 
> imageContours, contours, hierarchy = cv2.findContours(thresh, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
> 
> Getting this Error can you please help me to solve this....
> 
> Thanks In Advance

Updated code.
